apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: mongodb-primary-router-v3
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'mongodb-primary-router:3'
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: 'git@github.com:abarcloud/abar-templates.git'
      contextDir: 'mongodb-primary-router/3'
      type: Git
      sourceSecret:
        name: 'abarcloud-github-abar-templates'
    strategy:
      type: Docker
    triggers:
      - type: ConfigChange

- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations: ~
    generation: 1
    name: mongodb-primary-router
