apiVersion: v1
kind: Template
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: database-backup

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: database-backup-latest
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'database-backup:1.0'
    runPolicy: Serial
    source:
      git:
        ref: '<REPOSITORY_REF_HERE>'
        uri: '<REPOSITORY_URL_HERE>'
      contextDir: 'database-backup/latest'
      type: Git
    strategy:
      type: Docker
    triggers:
      - type: ConfigChange
