apiVersion: v1
kind: Template
metadata:
  name: postgresql-non-production
  annotations:
    openshift.io/display-name: PostgreSQL (non-production)
    description: "PostgreSQL v9.5 database service, with persistent storage. For more
      information about using this template, see https://docs.openshift.org/latest/using_images/db_images/postgresql.html.\n\nNOTE:
      We do not yet recommend using this in production. For production we recommend
      using our managed PostgreSQL which offers a master/slave High-Availability setup
      with scheduled backups. See https://docs.abarcloud.com/additional-services/postgres.html
      for more details. \nScaling to more than one replica is not supported."
    iconClass: icon-postgresql
    tags: database,postgresql
    template.openshift.io/long-description: This template provides a standalone PostgreSQL
      server with a database created.  The database is stored on persistent storage.  The
      database name, username, and password are chosen via parameters when provisioning
      this service.
    template.openshift.io/provider-display-name: Red Hat, Inc. & AbarCloud
    template.openshift.io/documentation-url: https://docs.openshift.org/latest/using_images/db_images/postgresql.html
message: |-
  The following service(s) have been created in your project: ${SERVICE_NAME}.

         Username: ${POSTGRESQL_USER}
         Password: ${POSTGRESQL_PASSWORD}
    Database Name: ${POSTGRESQL_DATABASE}
   Connection URL: postgresql://${SERVICE_NAME}:5432/

  For more information about using this template, see https://github.com/sclorg/postgresql-container/blob/master/9.5.
objects:

- apiVersion: v1
  kind: Secret
  metadata:
    name: "${SERVICE_NAME}"
  stringData:
    database-user: "${POSTGRESQL_USER}"
    database-password: "${POSTGRESQL_PASSWORD}"

- apiVersion: v1
  kind: Service
  metadata:
    name: "${SERVICE_NAME}"
    creationTimestamp:
  spec:
    ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 0
    selector:
      name: "${SERVICE_NAME}"
    type: ClusterIP
    sessionAffinity: None
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "${SERVICE_NAME}"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${VOLUME_CAPACITY}"

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "${SERVICE_NAME}"
    creationTimestamp:
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ConfigChange
    replicas: 1
    selector:
      name: "${SERVICE_NAME}"
    template:
      metadata:
        creationTimestamp:
        labels:
          name: "${SERVICE_NAME}"
      spec:
        containers:
        - name: postgresql
          image: "172.30.150.55:5000/openshift/postgresql:9.5"
          ports:
          - containerPort: 5432
            protocol: TCP
          readinessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 5
            exec:
              command:
              - "/bin/sh"
              - "-i"
              - "-c"
              - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
                'SELECT 1'
          livenessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 30
            tcpSocket:
              port: 5432
          env:
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: "${SERVICE_NAME}"
                key: database-user
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "${SERVICE_NAME}"
                key: database-password
          - name: POSTGRESQL_DATABASE
            value: "${POSTGRESQL_DATABASE}"
          resources:
            limits:
              memory: "${MEMORY_LIMIT}"
          volumeMounts:
          - name: "${SERVICE_NAME}-data"
            mountPath: "/var/lib/pgsql/data"
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: IfNotPresent
          capabilities: {}
          securityContext:
            capabilities: {}
            privileged: false
        volumes:
        - name: "${SERVICE_NAME}-data"
          persistentVolumeClaim:
            claimName: "${SERVICE_NAME}"
        restartPolicy: Always
        dnsPolicy: ClusterFirst
  status: {}

parameters:
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Maximum amount of memory the container can use, e.g. 500Mi, 1Gi. This
    can be modified later in the DeploymentConfig.
  value: 200Mi
  required: true
- name: SERVICE_NAME
  displayName: Service Name
  description: The name used when creating the required deployment config, build config,
    service etc. Must be unique and contain only lower-case letters.
  value: postgresql
  required: true
- name: POSTGRESQL_USER
  displayName: PostgreSQL Connection Username
  description: 'Username for PostgreSQL user that will be used for accessing the database.
    Leave this empty if you''d like it to be auto-generated. Note: This cannot be
    ''postgres'' since this user is already created by the image.'
  generate: expression
  from: user[A-Z0-9]{3}
  required: true
- name: POSTGRESQL_PASSWORD
  displayName: PostgreSQL Connection Password
  description: Password for the PostgreSQL connection user. Leave this empty if you'd
    like it to be auto-generated.
  generate: expression
  from: "[a-zA-Z0-9]{16}"
  required: true
- name: POSTGRESQL_DATABASE
  displayName: PostgreSQL Database Name
  description: Name of the PostgreSQL database accessed. You can create more from
    the PostgreSQL terminal later.
  value: sampledb
  required: true
- name: VOLUME_CAPACITY
  displayName: Volume Capacity
  description: Volume space available for data, e.g. 2Gi, 5Gi.
  value: 2Gi
  required: true
