apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: kibana-latest
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'kibana:6.1.1'
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: 'https://github.com/abarcloud/abar-templates.git'
      contextDir: 'kibana/latest'
      type: Git
    strategy:
      type: Docker
    triggers:
      - type: ConfigChange

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: kibana
