apiVersion: v1
kind: Template
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: mongodb

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: mongodb-latest
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'mongodb:3.6'
    runPolicy: Serial
    source:
      contextDir: "3.6"
      git:
        ref: master
        uri: 'https://github.com/abarcloud/mongodb-container.git'
      type: Git
    strategy:
      type: Docker
    triggers:
      - type: ConfigChange

