apiVersion: v1
kind: Template
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: mongodb
    annotations:
      openshift.io/display-name: MongoDB
  spec:
    tags:
    - name: '3.2'
      annotations:
        openshift.io/display-name: MongoDB 3.2
        description: Provides a MongoDB 3.2 database on CentOS 7. For more information
          about using this database image, including OpenShift considerations, see https://github.com/sclorg/mongodb-container/tree/master/3.2/README.md.
        iconClass: icon-mongodb
        tags: mongodb
        version: '3.2'
      from:
        kind: DockerImage
        name: centos/mongodb-32-centos7:latest
