apiVersion: v1
kind: Template
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: postgresql
  spec:
    tags:
    - name: latest
      annotations:
        openshift.io/display-name: PostgreSQL (Latest)
        description: |-
          Provides a PostgreSQL database on CentOS 7. For more information about using this database image, see https://github.com/sclorg/postgresql-container/tree/master/9.5.

          WARNING: By selecting this tag, your application will automatically update to use the latest version of PostgreSQL available on AbarCloud, including major versions updates.
        iconClass: icon-postgresql
        tags: postgresql
      from:
        kind: ImageStreamTag
        name: '9.5'
    - name: '9.5'
      annotations:
        openshift.io/display-name: PostgreSQL 9.5
        description: Provides a PostgreSQL 9.5 database on CentOS 7. For more information
          about using this database image, see https://github.com/sclorg/postgresql-container/tree/master/9.5
        iconClass: icon-postgresql
        tags: postgresql
        version: '9.5'
      from:
        kind: DockerImage
        name: centos/postgresql-95-centos7:latest
