apiVersion: v1
kind: Template
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: mongodb-primary-router

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: mongodb-primary-router-latest
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'mongodb-primary-router:3.6'
    runPolicy: Serial
    source:
      git:
        ref: '<REPOSITORY_REF_HERE>'
        uri: '<REPOSITORY_URL_HERE>'
      contextDir: 'mongodb-primary-router/latest'
      type: Git
    strategy:
      type: Docker
    triggers:
      - type: ConfigChange
