apiVersion: v1
kind: Template
metadata:
  name: redis

objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: redis-latest
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'redis:4.0.9'
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: 'https://github.com/abarcloud/abar-templates.git'
      contextDir: 'redis/latest'
      type: Git
    strategy:
      type: Docker
    triggers:
      - type: ConfigChange

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: redis