apiVersion: v1
kind: Template
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: rabbitmq

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: rabbitmq-management-latest
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'rabbitmq:3.6-management'
    runPolicy: Serial
    source:
      git:
        ref: '<REPOSITORY_REF_HERE>'
        uri: '<REPOSITORY_URL_HERE>'
      contextDir: 'rabbitmq/latest-management'
      type: Git
    strategy:
      type: Docker
    triggers:
      - type: ConfigChange
