apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: rabbitmq-management-latest
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'rabbitmq:3.6-management'
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: 'https://github.com/abarcloud/abar-templates.git'
      contextDir: 'rabbitmq/latest-management'
      type: Git
    strategy:
      type: Docker
    triggers:
      - type: ConfigChange

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: rabbitmq
