apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: wordpress-v4-php7-apache
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'wordpress:4-php7-apache'
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: 'git@github.com:abarcloud/abar-templates.git'
      contextDir: 'wordpress/4-php7-apache'
      type: Git
      sourceSecret:
        name: 'abarcloud-github-abar-templates'
    strategy:
      type: Docker
    triggers:
      - type: ConfigChange

- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations: ~
    generation: 1
    name: wordpress
