apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: log-analyzer-v1
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'log-analyzer:1.0'
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: 'git@github.com:abarcloud/abar-templates.git'
      contextDir: 'log-analyzer/1'
      type: Git
      sourceSecret:
        name: 'abarcloud-github-abar-templates'
    strategy:
      type: Docker
    triggers:
      - type: ConfigChange

- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations: ~
    generation: 1
    name: log-analyzer
  spec:
    tags:
    - name: latest
      annotations:
        openshift.io/display-name: Log Analyzer (Latest)
        iconClass: icon-log
        tags: log,analyzer
      from:
        kind: ImageStreamTag
        name: '1.0'