apiVersion: v1
kind: Template
message: |-
  The following service have been created in your project: ${SERVICE_NAME}.

  You must change your application route (or create a new route) to point to "${SERVICE_NAME}" service.
metadata:
  name: varnish
  annotations:
    description: |-
      Varnish Cache v4.1.9 is a web application accelerator and is really, really fast.
      It typically speeds up delivery with a factor of 300 - 1000x, depending on your architecture.
    iconClass: icon-varnish
    openshift.io/display-name: Varnish Cache
    tags: cache,varnish
    template.openshift.io/documentation-url: https://docs.abarcloud.com/additional-services/varnish.html
    template.openshift.io/provider-display-name: AbarCloud

objects:

- apiVersion: v1
  kind: Service
  metadata:
    name: ${SERVICE_NAME}
    labels:
      app: ${SERVICE_NAME}
  spec:
    ports:
      - name: varnish
        nodePort: 0
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      app: ${SERVICE_NAME}

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      app: ${SERVICE_NAME}
      deploymentconfig: ${SERVICE_NAME}
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${SERVICE_NAME}
          deploymentconfig: ${SERVICE_NAME}
      spec:
        containers:
          - image: '172.30.150.55:5000/%NAMESPACE_HERE%/varnish:4.1.9'
            imagePullPolicy: Always
            name: ${SERVICE_NAME}
            env:
            - name: TARGET_SERVICE_HOST
              value: ${TARGET_SERVICE_HOST}
            - name: TARGET_SERVICE_PORT
              value: ${TARGET_SERVICE_PORT}
            - name: REMOTE_PURGER
              value: "10.128.0.0/14" # Pods IP Range
            - name: VARNISH_MEMORY
              valueFrom:
                resourceFieldRef:
                  divisor: '0'
                  resource: limits.memory
            ports:
            - containerPort: 8080
              protocol: TCP
            resources:
              limits:
                memory: ${MEMORY_LIMIT}
            livenessProbe:
              failureThreshold: 3
              initialDelaySeconds: 20
              periodSeconds: 60
              successThreshold: 1
              tcpSocket:
                port: 8080
              timeoutSeconds: 2
            readinessProbe:
              failureThreshold: 3
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              tcpSocket:
                port: 8080
              timeoutSeconds: 2
            terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange

parameters:
- displayName: Varnish Service Name
  description: The name used when creating the required DeploymentConfig and Service. Must be unique and contain only lower-case letters.
  name: SERVICE_NAME
  required: true
  value: varnish
- displayName: Application Service Hostname
  description: The internal hostname of your web application Service that you want to put behind Varnish Cache.
  name: TARGET_SERVICE_HOST
  required: true
  value: my-app
- displayName: Application Service Port
  description: The port of your web application service that you want to put behind Varnish Cache.
  name: TARGET_SERVICE_PORT
  required: true
  value: "8080"
- displayName: Memory Limit
  description: Maximum amount of memory the container can use, e.g. 200Mi, 500Mi, 1Gi. This
    can be modified later in the DeploymentConfig.
  name: MEMORY_LIMIT
  required: true
  value: 200Mi