apiVersion: v1
kind: Template
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: redis-commander

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: redis-commander-latest
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'redis-commander:0.4.5'
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: 'https://github.com/abarcloud/abar-templates.git'
      contextDir: 'redis-commander/latest'
      type: Git
    strategy:
      type: Docker
    triggers:
      - type: ConfigChange
