apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: wordpress-latest-php7-apache
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'wordpress:4.8-php7-apache'
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: 'https://github.com/abarcloud/abar-templates.git'
      contextDir: 'wordpress/latest-php7-apache'
      type: Git
    strategy:
      type: Docker
    triggers:
      - type: ConfigChange

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: wordpress
