apiVersion: v1
kind: Template
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: wordpress

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: wordpress-latest-php7-apache
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'wordpress:4.8-php7-apache'
    runPolicy: Serial
    source:
      git:
        ref: '<REPOSITORY_REF_HERE>'
        uri: '<REPOSITORY_URL_HERE>'
      contextDir: 'wordpress/latest-php7-apache'
      type: Git
    strategy:
      type: Docker
    triggers:
      - type: ConfigChange
