apiVersion: v1
kind: Template
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: mysql
    annotations:
      openshift.io/display-name: MySQL
  spec:
    tags:
    - name: '5.7'
      annotations:
        openshift.io/display-name: MySQL 5.7
        description: Provides a MySQL 5.7 database on CentOS 7. For more information
          about using this database image, including OpenShift considerations, see https://github.com/sclorg/mysql-container/tree/master/5.7.
        iconClass: icon-mysql-database
        tags: mysql
        version: '5.7'
      from:
        kind: DockerImage
        name: docker.io/centos/mysql-57-centos7:latest
