apiVersion: v1
kind: Template
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: certbot

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: certbot-latest
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'certbot:latest'
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: 'https://github.com/abarcloud/abar-templates.git'
      contextDir: 'certbot/latest'
      type: Git
    strategy:
      type: Docker
    triggers:
      - type: ConfigChange
