apiVersion: v1
kind: Template
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: jenkins

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: jenkins-latest
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'jenkins:2-centos7-oc-v3.10'
    runPolicy: Serial
    source:
      git:
        ref: '<REPOSITORY_REF_HERE>'
        uri: '<REPOSITORY_URL_HERE>'
      contextDir: 'jenkins/latest'
      type: Git
    strategy:
      type: Docker
    triggers:
      - type: ConfigChange
