apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: varnish-v4
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'varnish:4.1.9'
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: 'https://github.com/abarcloud/abar-templates.git'
      contextDir: 'varnish/latest'
      type: Git
    strategy:
      type: Docker
    triggers:
      - type: ConfigChange

- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations: ~
    generation: 1
    name: varnish
  spec:
    tags:
    - name: '4'
      annotations:
        openshift.io/display-name: Varnish (Latest)
        iconClass: icon-postgresql
        tags: varnish
      from:
        kind: ImageStreamTag
        name: '4.1.9'
