apiVersion: v1
kind: Template
metadata:
  name: kafka
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: kafka

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: kafka-latest
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'kafka:1.0.0'
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: 'https://github.com/abarcloud/abar-templates.git'
      contextDir: 'kafka/latest'
      type: Git
    strategy:
      type: Docker
    triggers:
      - type: ConfigChange
